import { createRouter, createWebHistory } from "vue-router"

import {
  Index,

  // getting started
  Installation,
  ContributionGuide,
  Theme,

  // demos
  TwoColumnLayoutDemo,

  // components
  Accord,
  Alert,
  AlertDialog,
  AspectRatio,
  Avatar,
  Badge,
  Breadcrumb,
  Button,
  ButtonGroup,
  Calendar,
  Card,
  Carousel,
  Chart,
  Checkbox,
  Collapsible,
  Combobox,
  Command,
  ConfirmDialog,
  ContextMenu,
  Dialog,
  Drawer,
  DropdownMenu,
  Empty,
  Field,
  Flasher,
  Form,
  Heading,
  HoverCard,
  Input,
  InputGroup,
  InputOTP,
  Item,
  Kbd,
  Label,
  Menubar,
  NumberField,
  Pagination,
  PinInput,
  Popover,
  Progress,
  RadioGroup,
  RangeCalendar,
  Resizable,
  ScrollArea,
  Select,
  Separator,
  Sheet,
  Sidebar,
  Skeleton,
  Slider,
  Sonner,
  Spinner,
  Stepper,
  Switch,
  Table,
  Tabs,
  TagsInput,
  Textarea,
  Tip,
  Toggle,
  ToggleGroup,
  TwoColumnLayout,
} from "@app/pages"
import ArticleLayout from "@app/layouts/ArticleLayout.vue"
import ComponentLayout from "@app/layouts/ComponentLayout.vue"

const routes = [
  { path: "", component: Index },
  { path: "/demo/two-column-layout", component: TwoColumnLayoutDemo },
  {
    name: "Getting Started",
    children: [
      {
        name: "Installation",
        path: "/installation",
        component: Installation,
        meta: { layout: ArticleLayout, shadcn: true },
      },
      {
        name: "Theme",
        path: "/theme",
        component: Theme,
        meta: { layout: ArticleLayout, shadcn: true },
      },
      {
        name: "Contribution Guide",
        path: "/contribution-guide",
        component: ContributionGuide,
        meta: { layout: ArticleLayout, shadcn: true },
      },
    ],
  },
  {
    name: "Components",
    children: [
      {
        name: "Accord",
        path: "/components/accordion",
        component: Accord,
        meta: { layout: ComponentLayout },
      },
      {
        name: "Alert",
        path: "/components/alert",
        component: Alert,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Aspect Ratio",
        path: "/components/aspect-ratio",
        component: AspectRatio,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Avatar",
        path: "/components/avatar",
        component: Avatar,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Badge",
        path: "/components/badge",
        component: Badge,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Breadcrumb",
        path: "/components/breadcrumb",
        component: Breadcrumb,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Button",
        path: "/components/button",
        component: Button,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Button Group",
        path: "/components/button-group",
        component: ButtonGroup,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Carousel",
        path: "/components/carousel",
        component: Carousel,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Collapsible",
        path: "/components/collapsible",
        component: Collapsible,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Combobox",
        path: "/components/combobox",
        component: Combobox,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Command",
        path: "/components/command",
        component: Command,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Confirm Dialog",
        path: "/components/confirm-dialog",
        component: ConfirmDialog,
        meta: { layout: ComponentLayout, shadcn: false },
      },
      {
        name: "Context Menu",
        path: "/components/context-menu",
        component: ContextMenu,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Dropdown Menu",
        path: "/components/dropdown-menu",
        component: DropdownMenu,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Empty",
        path: "/components/empty",
        component: Empty,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Flasher",
        path: "/components/flasher",
        component: Flasher,
        meta: { layout: ComponentLayout },
      },
      {
        name: "Hover Card",
        path: "/components/hover-card",
        component: HoverCard,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Item",
        path: "/components/item",
        component: Item,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Kbd",
        path: "/components/kbd",
        component: Kbd,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Menubar",
        path: "/components/menubar",
        component: Menubar,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Popover",
        path: "/components/popover",
        component: Popover,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Progress",
        path: "/components/progress",
        component: Progress,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Scroll Area",
        path: "/components/scroll-area",
        component: ScrollArea,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Separator",
        path: "/components/separator",
        component: Separator,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Skeleton",
        path: "/components/skeleton",
        component: Skeleton,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Sonner",
        path: "/components/sonner",
        component: Sonner,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Spinner",
        path: "/components/spinner",
        component: Spinner,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Tip",
        path: "/components/tip",
        component: Tip,
        meta: { layout: ComponentLayout },
      },
    ],
  },
  {
    name: "Forms",
    children: [
      {
        name: "Calendar",
        path: "/components/calendar",
        component: Calendar,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Checkbox",
        path: "/components/checkbox",
        component: Checkbox,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Field",
        path: "/components/field",
        component: Field,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Form",
        path: "/components/form",
        component: Form,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Input",
        path: "/components/input",
        component: Input,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Input Group",
        path: "/components/input-group",
        component: InputGroup,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Input OTP",
        path: "/components/input-otp",
        component: InputOTP,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Label",
        path: "/components/label",
        component: Label,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Number Field",
        path: "/components/number-field",
        component: NumberField,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Pin Input",
        path: "/components/pin-input",
        component: PinInput,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Radio Group",
        path: "/components/radio-group",
        component: RadioGroup,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Range Calendar",
        path: "/components/range-calendar",
        component: RangeCalendar,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Select",
        path: "/components/select",
        component: Select,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Slider",
        path: "/components/slider",
        component: Slider,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Switch",
        path: "/components/switch",
        component: Switch,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Tags Input",
        path: "/components/tags-input",
        component: TagsInput,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Textarea",
        path: "/components/textarea",
        component: Textarea,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Toggle",
        path: "/components/toggle",
        component: Toggle,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Toggle Group",
        path: "/components/toggle-group",
        component: ToggleGroup,
        meta: { layout: ComponentLayout, shadcn: true },
      },
    ],
  },
  {
    name: "Page Layout",
    children: [
      {
        name: "Alert Dialog",
        path: "/components/alert-dialog",
        component: AlertDialog,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Card",
        path: "/components/card",
        component: Card,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Chart",
        path: "/components/chart",
        component: Chart,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Dialog (modal)",
        path: "/components/dialog",
        component: Dialog,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Drawer",
        path: "/components/drawer",
        component: Drawer,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Heading",
        path: "/components/heading",
        component: Heading,
        meta: { layout: ComponentLayout },
      },
      {
        name: "Pagination",
        path: "/components/pagination",
        component: Pagination,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Resizable",
        path: "/components/resizable",
        component: Resizable,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Sheet / Slideover",
        path: "/components/sheet",
        component: Sheet,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Sidebar",
        path: "/components/sidebar",
        component: Sidebar,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Stepper",
        path: "/components/stepper",
        component: Stepper,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Table",
        path: "/components/table",
        component: Table,
        meta: { layout: ComponentLayout, shadcn: true },
      },
      {
        name: "Tabs",
        path: "/components/tabs",
        component: Tabs,
        meta: { layout: ComponentLayout, shadcn: true },
      },
    ],
  },
  {
    name: "App Layouts",
    children: [
      {
        name: "Two Column",
        path: "/components/two-column-layout",
        component: TwoColumnLayout,
        meta: { layout: ComponentLayout },
      },
    ],
  },
]

const router = createRouter({
  history: createWebHistory(),
  linkActiveClass: "!font-bold",
  routes,
})

export default router
