// getting started
export { default as Index } from "./Index.vue"
export { default as ContributionGuide } from "./contribution-guide.md"
export { default as Installation } from "./installation.md"
export { default as Theme } from "./theme.md"

// components
export { default as AlertDialog } from "./components/AlertDialog.vue"
export { default as Avatar } from "./components/Avatar.vue"
export { default as Badge } from "./components/Badge.vue"
export { default as Button } from "./components/Button.vue"
export { default as Command } from "./components/Command.vue"
export { default as Dialog } from "./components/Dialog.vue"
export { default as DropdownMenu } from "./components/DropdownMenu.vue"
export { default as Input } from "./components/Input.vue"
export { default as Label } from "./components/Label.vue"
export { default as Notification } from "./components/Notification.vue"
export { default as Popover } from "./components/Popover.vue"
export { default as Sheet } from "./components/Sheet.vue"
export { default as Switch } from "./components/Switch.vue"
export { default as Toast } from "./components/Toast.vue"
